###############################################################################
# Common Environment server parameters

###############################################################################
# Octomap plugin


###############################################################################
# Point cloud plugin

###############################################################################
# Collision map plugins

###############################################################################
# Collision objects plugin

###############################################################################
# Compressed point cloud plugin

###############################################################################
# Interactive markers plugin

###############################################################################
# Limited point cloud plugin

###############################################################################
# 2D map plugin

###############################################################################
# Marker array plugin

###############################################################################
# Objtree plugin


